// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	TWITCH_APP_SECRET: string;
	TWITCH_CLIENT_ID: string;
	DATABASE_URL: string;
	LOCAL_DATABASE: string;
	ENCRYPTION_KEY: string;
}
